namespace Core
{
    public enum TokenType
    {
        Eof,
        Semicolon,
        Comma,
        
        // keywords
        Break,
        Do,
        Instanceof,
        Typeof,
        Case,
        Else,
        New,
        Var,
        Catch,
        Finally,
        Return,
        Void,
        Continue,
        For,
        Switch,
        While,
        Debugger,
        Function,
        This,
        With,
        Default,
        If,
        Throw,
        Delete,
        In,
        Try,
        Class,
        Enum,
        Extends,
        Super,
        Const,
        Export,
        Import,
        Implements,
        Let,
        Private,
        Public,
        Interface,
        Package,
        Protected,
        Static,
        Yield,
        
        // Literals
        Null,
        Undefined,
        True,
        False,
        Number,
        Binary,
        Octal,
        Hexadecimal,
        String,
        Identifier,
        Regex,
        
        // Braces
        ParenOpen,
        ParenClose,
        CurlyOpen,
        CurlyClose,
        SquareOpen,
        SquareClose,

        // Operators
        Plus,
        Minus,
        Multiply,
        Divide,
        Power,
        Equal,
        NotEqual,
        Less,
        LessEqual,
        Greater,
        GreaterEqual,
        BitAnd,
        BitOr,
        BitXor,
        And,
        Or,
        Xor,
        ShiftLeft,
        ShiftRight,
        Assign,
        
    }
}